name: samabus
description: A new Flutter project. # Assuming a default description
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Example SDK constraint, adjust if needed

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^1.10.7
  provider: ^6.0.5
  intl: ^0.18.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Example linter, adjust if needed

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg 